version: '3.8'

services:
  mongo1:
    image: mongo:7
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - ./mongo1/data:/data/db
    networks:
      mongo-cluster:
        ipv4_address: 172.26.0.11
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo2:
    image: mongo:7
    container_name: mongo2
    ports:
      - "27018:27017"
    volumes:
      - ./mongo2/data:/data/db
    networks:
      mongo-cluster:
        ipv4_address: 172.26.0.12
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo3:
    image: mongo:7
    container_name: mongo3
    ports:
      - "27019:27017"
    volumes:
      - ./mongo3/data:/data/db
    networks:
      mongo-cluster:
        ipv4_address: 172.26.0.13
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  arbiter:
    image: mongo:7
    container_name: arbiter
    ports:
      - "27020:27017"
    networks:
      mongo-cluster:
        ipv4_address: 172.26.0.14
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

networks:
  mongo-cluster:
      external: true
    #    name: mongo-cluster
    #driver: bridge
    #ipam:
    #  config:
    #    - subnet: 172.26.0.0/24
